### ISSUE TITLE
How to handle private repos

### ISSUE THREAD

**Issue by a-a-hofmann** [mp-access/Course-Service#10]

**Comment by Haeri** [comment]
Create github application so private repos can add us as contributor.

**Comment by mech-studi** [comment]
Github/Gitlab/Bitbucket ... wie können wir ServiceAccounts oder so etwas benutzen?

**Comment by a-a-hofmann** [comment]
So I think I found a way to handle private repos which works nicely for all of the three major git apps:
**Deploy keys**.

Basically ssh keys for service accounts which can be used to grant per-repository access.

### Fact-sheet:
- On our side this requires only creating a private SSH key (or ideally one for each Github/Bitbucket/Gitlab), **we don't have to change any code**
- we don't need to hold user credentials or create a dummy account which the user has to add as a collaborator to the repository
- Access is read-only (write optional) and per-repository
- The same mechanism works for:
    - Github: https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys
    - Bitbucket: https://confluence.atlassian.com/bitbucket/access-keys-294486051.html
    - Gitlab: https://docs.gitlab.com/ee/ssh/#per-repository-deploy-keys

### Onboarding
The onboarding process is mostly the same as before with an added first step:

1. Course owner adds our public key to its repo (we could include our *public keys* + links to documentation on a page somewhere on our site)
2. Course owner contacts an admin to create a new course and gives the admin the url as an ssh:// resource
3. Admin adds ssh:// URI to the `repositories.json`
4. ???
5. Profit
