### ISSUE TITLE
As a user I want to see my grade for an assignment

### ISSUE THREAD

**Issue by a-a-hofmann** [mp-access/Course-Service#116]

**Comment by mech-studi** [comment]
Mit Philip und Alex besprochen:

Als Resultat für eine Übung wird die letzte gültige Abgabe (Submission) genommen. Eine Abgabe ist gültig wenn sie zur aktuellen Übungsversion passt und ist mit einem Valid-Flag gekennzeichnet. 
Das Valid-Flag wird von einem Prozess gesetzt, der gestartet wird, wenn eine neue Übungsversion erstellt wird.
