### ISSUE TITLE
Invalidate Exercise Submissions, when updating exercise

### ISSUE THREAD

**Issue by mech-studi** [mp-access/Course-Service#126]
Neuer Task, der ausgeführt wird wenn eine neue Übungsversion erstellt wird. Der Task setzt Valid/Invalid Flag für die Übungsabgaben der Studenten.

**Comment by Haeri** [comment]
Submission model need a flag (isInvalid).

**Comment by a-a-hofmann** [comment]
isInvalid iff githashes are not equal
