### ISSUE TITLE
Implement private repo solution with hash

### ISSUE THREAD

**Issue by Haeri** [mp-access/Course-Service#145]
Use this #10

**Comment by a-a-hofmann** [comment]
How-to:

Create an RSA key pair with:
`ssh-keygen -t rsa -m PEM -C "access@ifi.uzh.ch"`
Call the key `id_gitlab`

From private repository on Gitlab:
`Settings -> Repository -> Deploy Keys (collapse) ->` Give a title to the key and paste contents of   `id_gitlab.pub`

For backend:
Add url as `git@gitlab.com:<private-repo>.git` to `repositories.json`

Make sure `~./ssh/config` include the following:

```
Host gitlab.com
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_gitlab
```
