### ISSUE TITLE
Dates are ignored

### ISSUE THREAD

**Issue by Haeri** [mp-access/Course-Service#175]
Assignment dates and Exercise dates need to be considered when sending a list to frontend. 
Also users with elevated roles should still be able to see unpublished exercises/asignments

**Comment by a-a-hofmann** [comment]
We also should also not accept any official submission after a deadline

**Comment by a-a-hofmann** [comment]
/courses
Should a course be visible before its start date?

/courses/id
(assignments of a course + course metadata)
- Normal users: Should assignment be visible before the start date: it could be visible but not clickable
- TAs: always all visible, clickable etc

/courses/id/assignments/

/courses/id/assignments/id
- Normal users: This should only be visible after the start date; should remain open after due date
- TAs: always visible

/exercises/id
- Normal users: Only after start date visible; should remain open after due date
- TAs: always visible

/exercises/id/files/id
- Normal users: Only after start date, solutions files after due date
- TAs: always

/submissions
Submitting exercises (all other endpoints can be triggered, would just return empty responses)
- Normal users: Submitting only permitted after start date; official submissions only permitted between start and end date; smoke tests could be allowed after due date
- TAs: always visible, always submittable

/admins/courses/{courseId}/assignments/{assignmentId}/results
- TAs only, at any time

/students/courses/{courseId}/results
- Any time, only own results viewable
