### ISSUE TITLE
Text & Choices Submissions allways isGraded False

### ISSUE THREAD

**Issue by mech-studi** [mp-access/Course-Service#182]
Send the correct isGraded information for submissions of type text, single- & multipe-choice.

**Comment by Haeri** [comment]
I tested and it is not frontends fault, It sends the same isGraded as it does for code submissions. Must be something in backend

**Comment by a-a-hofmann** [comment]
I don't see any `isGraded` being sent from text, single- & multiple-choice exercises. Am I missing something?

**Comment by a-a-hofmann** [comment]
Btw do we even need the graded flag for those exercises? Aren't these always graded?
