### ISSUE TITLE
Login button/redirect configuration

### ISSUE THREAD

**Issue by mech-studi** [mp-access/Course-Service#81]
Wie genauss muss oAuth/Keycloack login configuriert werden. 
Wenn ich bei mir auf den Login button (neuer button im header) werde ich nicht auf die Keycloack-Login-Seite weitergeleitet.

**Comment by a-a-hofmann** [comment]
Was passiert genau wenn du klickst? Wirst du einfach wieder auf den frontend redirected?

**Comment by a-a-hofmann** [comment]
Ah wahrscheinlich ist es weil ich den realm-config import kommentiert habe im `docker-compose-dev.yml` 
Ich habe es gerade updated: https://github.com/mp-access/Infrastructure/commit/bae595dc748df77a361e8d9150fecc7cbc74ab7e
